workflows:
  android-workflow:
    name: Codemagic Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.devj.gestantescontrolcompose"


    scripts:
      # ....
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          ./gradlew bundleRelease # -> to create the .aab
          # gradlew assembleRelease # -> to create the .apk

    artifacts:
      - app/build/outputs/**/*.aab
      - build/**/outputs/apk/**/*.apk